version: "3"
services:
  app-db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=registro
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - app-db